### ISSUE TITLE
No such file or directory: '/opt/vivaldi/resources/vivaldi/resources/vivaldi-splash-icon.svg'

### ISSUE THREAD

**Issue by artforlife** [LonMcGregor/VivaldiMods#33]
After upgrade to Vivaldi 5.2 on Ubuntu 20.04 LTS, I see the following when running `sudo python3 custom.py -i config.json`:

```
/opt/vivaldi/resources/vivaldi
WARNING - Uninstalling old mods
Traceback (most recent call last):
  File "custom.py", line 233, in <module>
    install()
  File "custom.py", line 58, in install
    uninstall()
  File "custom.py", line 75, in uninstall
    update_splash_screen('#d4d4d4', 'rgba(0, 0, 0, 0.1)')
  File "custom.py", line 196, in update_splash_screen
    with open(SPLASH_SVG, 'r') as svgfile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/vivaldi/resources/vivaldi/resources/vivaldi-splash-icon.svg'
(base) ➜  VivaldiMods git:(master) ✗                                      

```

**Comment by LonMcGregor** [comment]
Looks like vivaldi has changed how the splash screen loads. For now, try commenting out lines 63 and 74, where "update_splash_screen()" is called.

**Comment by artforlife** [comment]
> Looks like vivaldi has changed how the splash screen loads. For now, try commenting out lines 63 and 74, where "update_splash_screen()" is called.

That is exactly what I have done. I did like the splash screen, though! :-)

**Comment by danielcarr** [comment]
FYI I have been getting the same on MacOs
```
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Vivaldi.app/Contents/Frameworks/Vivaldi Framework.framework/resources/vivaldi/resources/vivaldi-splash-icon.svg'
```

(The same solution works).
